// 客户端安全的站点配置（不依赖 Node.js fs）
export type Lang = "zh" | "en";

export interface PostFrontmatter {
  title: string;
  date: string;
  draft?: boolean;
  author?: string;
  tags?: string[];
  categories?: string[];
  summary?: string;
  description?: string;
  pinned?: boolean;
  pinnedDescription?: string;
  hiddenInHomeList?: boolean;
  showToc?: boolean;
  cover?: { image?: string; caption?: string; hidden?: boolean; relative?: boolean };
  references?: { title: string; url?: string; author?: string; year?: string }[];
  keywords?: string[];
  canonicalURL?: string;
}

export interface Post {
  slug: string;
  lang: Lang;
  title: string;
  date: string;
  author?: string;
  tags: string[];
  categories: string[];
  summary: string;
  description?: string;
  pinned: boolean;
  pinnedDescription?: string;
  hiddenInHomeList: boolean;
  showToc: boolean;
  cover?: PostFrontmatter["cover"];
  references?: PostFrontmatter["references"];
  keywords?: string[];
  content: string;
  filePath: string;
  wordCount: number;
  isAI: boolean;
}

export const SITE = {
  title: "wunai's blog",
  author: "wunai",
  url: "https://newblog.wunai.top",
  defaultLang: "zh" as Lang,
  description: "学习笔记与生活思考：数学、物理、化学、医学、技术文章集合",
  homeInfo: {
    zh: { title: "Hi there", content: "欢迎来到我的博客，这里记录我的学习笔记与生活思考。" },
    en: { title: "Hi there", content: "Welcome to my blog — notes on tech and life." },
  },
  menu: {
    zh: [
      { name: "首页", href: "/zh/" },
      { name: "文章", href: "/zh/posts/" },
      { name: "标签", href: "/zh/tags/" },
      { name: "搜索", href: "/zh/search/" },
      { name: "归档", href: "/zh/archives/" },
      { name: "DMCC", href: "https://dmcc.wunai.top/", external: true },
    ],
    en: [
      { name: "Home", href: "/en/" },
      { name: "Posts", href: "/en/posts/" },
      { name: "Tags", href: "/en/tags/" },
      { name: "Search", href: "/en/search/" },
      { name: "Archives", href: "/en/archives/" },
      { name: "DMCC", href: "https://dmcc.wunai.top/", external: true },
    ],
  },
  i18n: {
    zh: { home: "首页", posts: "文章", tags: "标签", search: "搜索", archives: "归档", categories: "分类", prev: "上一篇", next: "下一篇", readingTime: "分钟阅读", words: "字", pinned: "置顶", aiWarning: "本文由 AI 生成，可能存在误区，斟酌阅读！！", comments: "评论", searchPlaceholder: "输入关键词搜索", allPosts: "全部文章", onThisPage: "本页目录" },
    en: { home: "Home", posts: "Posts", tags: "Tags", search: "Search", archives: "Archives", categories: "Categories", prev: "Previous", next: "Next", readingTime: "min read", words: "words", pinned: "Pinned", aiWarning: "This article was generated by AI and may contain inaccuracies. Read with caution!", comments: "Comments", searchPlaceholder: "Search posts...", allPosts: "All Posts", onThisPage: "On this page" },
  },
};
